require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'

platform :ios, '11.0'

target 'Helpt' do
  use_unimodules!
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'react-native-plaid-link-sdk', :path => '../node_modules/react-native-plaid-link-sdk'

  target 'HelptTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!({ 'Flipper' => '0.81.0' })
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
end

target 'Helpt-tvOS' do
  # Pods for Helpt-tvOS

  target 'Helpt-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
